#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 官方最新开发版openwrt动态DHCP 使用docker 

name: openwrt-DHCP-zip
on:
  repository_dispatch:
  workflow_dispatch:
   
jobs:

  build_openwrt:
    name: Build OpenWrt firmware
    runs-on: ubuntu-latest
    
    steps:

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update 
          sudo -E apt-get -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
          
      - name: Clone source code
        run: |
         wget https://github.com/openwrt/openwrt/archive/refs/tags/v23.05.2.zip
         unzip v23.05.2.zip
         mv openwrt-23.05.2 openwrt
      - name: Update feeds
        run: |
          cd openwrt
          cat >> feeds.conf.default <<EOF 
          src-git kenzo https://github.com/kenzok8/openwrt-packages
          src-git small https://github.com/kenzok8/small
          #src-git ddd https://github.com/wandduse/openwrt-packages
          EOF
          # 静态 to DHCP
           sed -i 's/-static/-dhcp/g' package/base-files/files/lib/functions/uci-defaults.sh
           sed -i 's/none/dhcp/g' package/base-files/files/bin/config_generate
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          # sed -i 's/Authorization Required/wanuse.com/g' feeds/luci/modules/luci-base/ucode/template/sysauth.ut
          sed -i 's/Authorization Required/openwrt v23.05.2 wanuse.com/g' feeds/luci/themes/luci-theme-bootstrap/htdocs/luci-static/resources/view/bootstrap/sysauth.js
          sed -i 's/需要授权/openwrt v23.05.2 wanuse.com/g' feeds/luci/modules/luci-base/po/zh_Hans/base.po
          
          
     
      - name: Generate configuration file
        run: |
          cd openwrt
          
          rm -f ./.config*
          rm -rf ./tmp && rm -rf .config
          touch ./.config          
          cat >> .config <<EOF 
          # CONFIG_VMDK_IMAGES is not set
          # CONFIG_GRUB_EFI_IMAGES is not set
          # CONFIG_TARGET_ROOTFS_EXT4FS is not set
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_TARGET_IMAGES_GZIP=y
          CONFIG_TARGET_ROOTFS_TARGZ=y
          CONFIG_TARGET_ROOTFS_PARTSIZE=1024
        
          EOF
          #
          # ===============================================================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
          
      - name: Start SSH via tmate
        uses: rdp-studio/ssh2actions@main
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      
      - name: up config
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_config
          path: ./openwrt/.config    
      
      - name: Make download
        run: |
          cd openwrt
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h
      - name: Compile firmware
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df 
