name: Build OpenWrt 23.05.2 ai

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点自动编译

env:
  OPENWRT_REPO: 'https://github.com/openwrt/openwrt/tree/openwrt-23.05' # OpenWrt源码仓库
  OPENWRT_BRANCH: 'openwrt-23.05' # OpenWrt版本分支
  FEEDS_CONF: 'feeds.conf.default' # feeds配置文件
  CONFIG_FILE: '.config' # 编译配置文件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ env.OPENWRT_REPO }}
        ref: ${{ env.OPENWRT_BRANCH }}
        
    - name: Checkout custom packages
      uses: actions/checkout@v2
      with:
        repository: kiddin9/openwrt-packages
        ref: main # 或者你想要的分支
        path: packages # 存放插件的目录
  
    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib

    - name: Install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a -p packages

    - name: Load custom configuration
      run: |
        cp ${{ github.workspace }}/${{ env.CONFIG_FILE }} .config

    - name: Cache build directories
      uses: actions/cache@v2
      with:
        path: |
          bin
          build_dir
          staging_dir
        key: ${{ runner.os }}-openwrt-${{ hashFiles('**/${{ env.CONFIG_FILE }}') }}
        restore-keys: |
          ${{ runner.os }}-openwrt-

    - name: Compile OpenWrt
      run: |
        make defconfig
        make -j$(nproc)
